// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum BleApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Power/authorization state of the host Bluetooth adapter.
enum BleAdapterState: Int, CaseIterable {
  /// Not yet reported by the platform.
  case unknown = 0
  /// No BLE radio, or the radio cannot do what the mesh needs.
  case unsupported = 1
  /// The user denied Bluetooth permission, or it was never granted.
  case unauthorized = 2
  /// Radio present but switched off.
  case poweredOff = 3
  /// Ready to scan and advertise.
  case poweredOn = 4
}

/// Which side of the connection we are on for a given link.
///
/// A peer can be reachable over two links at once (we connected out, they
/// connected in). Collapsing links into peers is protocol-layer work in Dart.
enum BleLinkRole: Int, CaseIterable {
  /// We are the GATT client; we connected to their advertisement.
  case central = 0
  /// We are the GATT server; they connected to our advertisement.
  case peripheral = 1
}

enum BlePermissionState: Int, CaseIterable {
  case granted = 0
  case denied = 1
  /// Denied with "don't ask again" / restricted by policy. Only a trip to
  /// system settings can change this, so the UI must say so.
  case permanentlyDenied = 2
  /// The platform needs no runtime permission for this (e.g. macOS).
  case notRequired = 3
}

enum BleErrorCode: Int, CaseIterable {
  case bluetoothOff = 0
  case permissionDenied = 1
  case unsupported = 2
  case advertisingFailed = 3
  case scanFailed = 4
  case connectionFailed = 5
  case writeFailed = 6
  /// Not named `internal`: Pigeon would emit `case internal` in Swift, which
  /// is a reserved word there.
  case internalError = 7
}

enum BleEventKind: Int, CaseIterable {
  case adapterState = 0
  case linkUp = 1
  case linkDown = 2
  case frame = 3
  case error = 4
}

/// What this device's radio can actually do.
///
/// Plenty of budget Android hardware can scan but cannot advertise. Such a
/// device can still receive from the mesh but cannot be discovered, so the UI
/// must degrade honestly instead of pretending the mesh is healthy.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BleCapabilities: Hashable, CustomStringConvertible {
  var supportsCentral: Bool
  var supportsPeripheral: Bool
  var platformName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleCapabilities? {
    let supportsCentral = pigeonVar_list[0] as! Bool
    let supportsPeripheral = pigeonVar_list[1] as! Bool
    let platformName = pigeonVar_list[2] as! String

    return BleCapabilities(
      supportsCentral: supportsCentral,
      supportsPeripheral: supportsPeripheral,
      platformName: platformName
    )
  }
  func toList() -> [Any?] {
    return [
      supportsCentral,
      supportsPeripheral,
      platformName,
    ]
  }
  static func == (lhs: BleCapabilities, rhs: BleCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BleApiPigeonInternal.deepEquals(lhs.supportsCentral, rhs.supportsCentral) && BleApiPigeonInternal.deepEquals(lhs.supportsPeripheral, rhs.supportsPeripheral) && BleApiPigeonInternal.deepEquals(lhs.platformName, rhs.platformName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleCapabilities")
    BleApiPigeonInternal.deepHash(value: supportsCentral, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: supportsPeripheral, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: platformName, hasher: &hasher)
  }

  public var description: String {
    return "BleCapabilities(supportsCentral: \(String(describing: supportsCentral)), supportsPeripheral: \(String(describing: supportsPeripheral)), platformName: \(String(describing: platformName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleConfig: Hashable, CustomStringConvertible {
  /// 128-bit service UUID the mesh advertises and scans for.
  var serviceUuid: String
  /// Single read/write/notify characteristic that carries every frame.
  var characteristicUuid: String
  /// Short advertised name. The advertisement budget is 31 bytes, so this goes
  /// in the scan response and should stay under ~12 characters.
  var advertisedName: String
  /// Soft cap on simultaneous links. Android's hard limit is device-dependent
  /// (often 7) and exceeding it fails opaquely.
  var maxConcurrentLinks: Int64
  /// Duty cycle for scanning. Android throttles apps to 5 `startScan` calls
  /// per 30s, so these values must stay well clear of that.
  var scanWindowMs: Int64
  var scanRestMs: Int64
  var connectionTimeoutMs: Int64
  /// Android only: run inside a `connectedDevice` foreground service so the
  /// mesh survives backgrounding. iOS uses background modes instead.
  var enableBackground: Bool
  var backgroundNotificationTitle: String
  var backgroundNotificationBody: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleConfig? {
    let serviceUuid = pigeonVar_list[0] as! String
    let characteristicUuid = pigeonVar_list[1] as! String
    let advertisedName = pigeonVar_list[2] as! String
    let maxConcurrentLinks = pigeonVar_list[3] as! Int64
    let scanWindowMs = pigeonVar_list[4] as! Int64
    let scanRestMs = pigeonVar_list[5] as! Int64
    let connectionTimeoutMs = pigeonVar_list[6] as! Int64
    let enableBackground = pigeonVar_list[7] as! Bool
    let backgroundNotificationTitle = pigeonVar_list[8] as! String
    let backgroundNotificationBody = pigeonVar_list[9] as! String

    return BleConfig(
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      advertisedName: advertisedName,
      maxConcurrentLinks: maxConcurrentLinks,
      scanWindowMs: scanWindowMs,
      scanRestMs: scanRestMs,
      connectionTimeoutMs: connectionTimeoutMs,
      enableBackground: enableBackground,
      backgroundNotificationTitle: backgroundNotificationTitle,
      backgroundNotificationBody: backgroundNotificationBody
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      characteristicUuid,
      advertisedName,
      maxConcurrentLinks,
      scanWindowMs,
      scanRestMs,
      connectionTimeoutMs,
      enableBackground,
      backgroundNotificationTitle,
      backgroundNotificationBody,
    ]
  }
  static func == (lhs: BleConfig, rhs: BleConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BleApiPigeonInternal.deepEquals(lhs.serviceUuid, rhs.serviceUuid) && BleApiPigeonInternal.deepEquals(lhs.characteristicUuid, rhs.characteristicUuid) && BleApiPigeonInternal.deepEquals(lhs.advertisedName, rhs.advertisedName) && BleApiPigeonInternal.deepEquals(lhs.maxConcurrentLinks, rhs.maxConcurrentLinks) && BleApiPigeonInternal.deepEquals(lhs.scanWindowMs, rhs.scanWindowMs) && BleApiPigeonInternal.deepEquals(lhs.scanRestMs, rhs.scanRestMs) && BleApiPigeonInternal.deepEquals(lhs.connectionTimeoutMs, rhs.connectionTimeoutMs) && BleApiPigeonInternal.deepEquals(lhs.enableBackground, rhs.enableBackground) && BleApiPigeonInternal.deepEquals(lhs.backgroundNotificationTitle, rhs.backgroundNotificationTitle) && BleApiPigeonInternal.deepEquals(lhs.backgroundNotificationBody, rhs.backgroundNotificationBody)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleConfig")
    BleApiPigeonInternal.deepHash(value: serviceUuid, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: characteristicUuid, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: advertisedName, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: maxConcurrentLinks, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: scanWindowMs, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: scanRestMs, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: connectionTimeoutMs, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: enableBackground, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: backgroundNotificationTitle, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: backgroundNotificationBody, hasher: &hasher)
  }

  public var description: String {
    return "BleConfig(serviceUuid: \(String(describing: serviceUuid)), characteristicUuid: \(String(describing: characteristicUuid)), advertisedName: \(String(describing: advertisedName)), maxConcurrentLinks: \(String(describing: maxConcurrentLinks)), scanWindowMs: \(String(describing: scanWindowMs)), scanRestMs: \(String(describing: scanRestMs)), connectionTimeoutMs: \(String(describing: connectionTimeoutMs)), enableBackground: \(String(describing: enableBackground)), backgroundNotificationTitle: \(String(describing: backgroundNotificationTitle)), backgroundNotificationBody: \(String(describing: backgroundNotificationBody)))"
  }
}

/// One physical connection. Not a peer identity.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BleLink: Hashable, CustomStringConvertible {
  /// Opaque, stable for the lifetime of this connection.
  var linkId: String
  var role: BleLinkRole
  /// Platform device handle (Android MAC or iOS/macOS CBPeripheral UUID).
  /// Not stable across reboots on iOS and randomized on Android — never treat
  /// it as an identity.
  var remoteId: String
  /// Largest frame that may be handed to [BleMeshHostApi.send] on this
  /// link. Dart fragments to this; the native side never fragments.
  var maxFrameSize: Int64
  var connectedAtMs: Int64
  var rssi: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleLink? {
    let linkId = pigeonVar_list[0] as! String
    let role = pigeonVar_list[1] as! BleLinkRole
    let remoteId = pigeonVar_list[2] as! String
    let maxFrameSize = pigeonVar_list[3] as! Int64
    let connectedAtMs = pigeonVar_list[4] as! Int64
    let rssi: Int64? = nilOrValue(pigeonVar_list[5])

    return BleLink(
      linkId: linkId,
      role: role,
      remoteId: remoteId,
      maxFrameSize: maxFrameSize,
      connectedAtMs: connectedAtMs,
      rssi: rssi
    )
  }
  func toList() -> [Any?] {
    return [
      linkId,
      role,
      remoteId,
      maxFrameSize,
      connectedAtMs,
      rssi,
    ]
  }
  static func == (lhs: BleLink, rhs: BleLink) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BleApiPigeonInternal.deepEquals(lhs.linkId, rhs.linkId) && BleApiPigeonInternal.deepEquals(lhs.role, rhs.role) && BleApiPigeonInternal.deepEquals(lhs.remoteId, rhs.remoteId) && BleApiPigeonInternal.deepEquals(lhs.maxFrameSize, rhs.maxFrameSize) && BleApiPigeonInternal.deepEquals(lhs.connectedAtMs, rhs.connectedAtMs) && BleApiPigeonInternal.deepEquals(lhs.rssi, rhs.rssi)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleLink")
    BleApiPigeonInternal.deepHash(value: linkId, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: role, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: remoteId, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: maxFrameSize, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: connectedAtMs, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: rssi, hasher: &hasher)
  }

  public var description: String {
    return "BleLink(linkId: \(String(describing: linkId)), role: \(String(describing: role)), remoteId: \(String(describing: remoteId)), maxFrameSize: \(String(describing: maxFrameSize)), connectedAtMs: \(String(describing: connectedAtMs)), rssi: \(String(describing: rssi)))"
  }
}

/// One envelope for every event, carried on a single channel.
///
/// A single channel makes ordering structural rather than incidental: a frame
/// can never be delivered before the `linkUp` for its link.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BleEvent: Hashable, CustomStringConvertible {
  var kind: BleEventKind
  /// Set when [kind] is [BleEventKind.adapterState].
  var adapterState: BleAdapterState? = nil
  /// Set when [kind] is [BleEventKind.linkUp].
  var link: BleLink? = nil
  /// Set for [BleEventKind.linkDown], [BleEventKind.frame], and for errors
  /// that are attributable to a specific link.
  var linkId: String? = nil
  /// Set when [kind] is [BleEventKind.frame].
  var frame: FlutterStandardTypedData? = nil
  /// Set when [kind] is [BleEventKind.error].
  var errorCode: BleErrorCode? = nil
  /// Human-readable detail for diagnostics. Never shown raw to end users.
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleEvent? {
    let kind = pigeonVar_list[0] as! BleEventKind
    let adapterState: BleAdapterState? = nilOrValue(pigeonVar_list[1])
    let link: BleLink? = nilOrValue(pigeonVar_list[2])
    let linkId: String? = nilOrValue(pigeonVar_list[3])
    let frame: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])
    let errorCode: BleErrorCode? = nilOrValue(pigeonVar_list[5])
    let message: String? = nilOrValue(pigeonVar_list[6])

    return BleEvent(
      kind: kind,
      adapterState: adapterState,
      link: link,
      linkId: linkId,
      frame: frame,
      errorCode: errorCode,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      adapterState,
      link,
      linkId,
      frame,
      errorCode,
      message,
    ]
  }
  static func == (lhs: BleEvent, rhs: BleEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return BleApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && BleApiPigeonInternal.deepEquals(lhs.adapterState, rhs.adapterState) && BleApiPigeonInternal.deepEquals(lhs.link, rhs.link) && BleApiPigeonInternal.deepEquals(lhs.linkId, rhs.linkId) && BleApiPigeonInternal.deepEquals(lhs.frame, rhs.frame) && BleApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && BleApiPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleEvent")
    BleApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: adapterState, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: link, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: linkId, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: frame, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    BleApiPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "BleEvent(kind: \(String(describing: kind)), adapterState: \(String(describing: adapterState)), link: \(String(describing: link)), linkId: \(String(describing: linkId)), frame: \(String(describing: frame)), errorCode: \(String(describing: errorCode)), message: \(String(describing: message)))"
  }
}

private class BleApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleAdapterState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleLinkRole(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BlePermissionState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return BleCapabilities.fromList(self.readValue() as! [Any?])
    case 135:
      return BleConfig.fromList(self.readValue() as! [Any?])
    case 136:
      return BleLink.fromList(self.readValue() as! [Any?])
    case 137:
      return BleEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BleApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleAdapterState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleLinkRole {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BlePermissionState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleErrorCode {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleEventKind {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleCapabilities {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BleConfig {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BleLink {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BleEvent {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BleApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BleApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BleApiPigeonCodecWriter(data: data)
  }
}

class BleApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BleApiPigeonCodec(readerWriter: BleApiPigeonCodecReaderWriter())
}

var bleApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: BleApiPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BleMeshHostApi {
  func capabilities() throws -> BleCapabilities
  func adapterState() throws -> BleAdapterState
  func requestPermissions() async throws -> BlePermissionState
  /// Starts advertising, the GATT server, and scanning. Idempotent.
  func start(config: BleConfig) async throws
  /// Stops everything and drops all links. Idempotent.
  func stop() async throws
  /// Sends one frame on one link.
  ///
  /// Completes when the platform has actually transmitted it (write callback
  /// or notification-sent callback), which is what gives Dart real
  /// backpressure instead of a fire-and-forget hose.
  func send(linkId: String, frame: FlutterStandardTypedData) async throws
  func disconnect(linkId: String) async throws
  func links() throws -> [BleLink]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BleMeshHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BleApiPigeonCodec.shared }
  /// Sets up an instance of `BleMeshHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BleMeshHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let capabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.capabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.capabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      capabilitiesChannel.setMessageHandler(nil)
    }
    let adapterStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.adapterState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      adapterStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.adapterState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      adapterStateChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestPermissions()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    /// Starts advertising, the GATT server, and scanning. Idempotent.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! BleConfig
        Task { @MainActor in
          do {
            try await api.start(config: configArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Stops everything and drops all links. Idempotent.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.stop()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Sends one frame on one link.
    ///
    /// Completes when the platform has actually transmitted it (write callback
    /// or notification-sent callback), which is what gives Dart real
    /// backpressure instead of a fire-and-forget hose.
    let sendChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.send\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let linkIdArg = args[0] as! String
        let frameArg = args[1] as! FlutterStandardTypedData
        Task { @MainActor in
          do {
            try await api.send(linkId: linkIdArg, frame: frameArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let linkIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.disconnect(linkId: linkIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let linksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.links\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      linksChannel.setMessageHandler { _, reply in
        do {
          let result = try api.links()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      linksChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class EventsStreamHandler: PigeonEventChannelWrapper<BleEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.ble_mesh.BleMeshEventApi.events"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<BleEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: bleApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
