// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Power/authorization state of the host Bluetooth adapter.
enum BleAdapterState {
  /// Not yet reported by the platform.
  unknown,
  /// No BLE radio, or the radio cannot do what the mesh needs.
  unsupported,
  /// The user denied Bluetooth permission, or it was never granted.
  unauthorized,
  /// Radio present but switched off.
  poweredOff,
  /// Ready to scan and advertise.
  poweredOn;
}

/// Which side of the connection we are on for a given link.
///
/// A peer can be reachable over two links at once (we connected out, they
/// connected in). Collapsing links into peers is protocol-layer work in Dart.
enum BleLinkRole {
  /// We are the GATT client; we connected to their advertisement.
  central,
  /// We are the GATT server; they connected to our advertisement.
  peripheral;
}

enum BlePermissionState {
  granted,
  denied,
  /// Denied with "don't ask again" / restricted by policy. Only a trip to
  /// system settings can change this, so the UI must say so.
  permanentlyDenied,
  /// The platform needs no runtime permission for this (e.g. macOS).
  notRequired;
}

enum BleErrorCode {
  bluetoothOff,
  permissionDenied,
  unsupported,
  advertisingFailed,
  scanFailed,
  connectionFailed,
  writeFailed,
  /// Not named `internal`: Pigeon would emit `case internal` in Swift, which
  /// is a reserved word there.
  internalError;
}

enum BleEventKind {
  adapterState,
  linkUp,
  linkDown,
  frame,
  error;
}

/// What this device's radio can actually do.
///
/// Plenty of budget Android hardware can scan but cannot advertise. Such a
/// device can still receive from the mesh but cannot be discovered, so the UI
/// must degrade honestly instead of pretending the mesh is healthy.
class BleCapabilities {
  BleCapabilities({
    required this.supportsCentral,
    required this.supportsPeripheral,
    required this.platformName,
  });

  bool supportsCentral;

  bool supportsPeripheral;

  String platformName;

  List<Object?> _toList() {
    return <Object?>[
      supportsCentral,
      supportsPeripheral,
      platformName,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleCapabilities decode(Object result) {
    result as List<Object?>;
    return BleCapabilities(
      supportsCentral: result[0]! as bool,
      supportsPeripheral: result[1]! as bool,
      platformName: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(supportsCentral, other.supportsCentral) && _deepEquals(supportsPeripheral, other.supportsPeripheral) && _deepEquals(platformName, other.platformName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BleCapabilities(supportsCentral: $supportsCentral, supportsPeripheral: $supportsPeripheral, platformName: $platformName)';
  }
}

class BleConfig {
  BleConfig({
    required this.serviceUuid,
    required this.characteristicUuid,
    required this.advertisedName,
    this.maxConcurrentLinks = 6,
    this.scanWindowMs = 10000,
    this.scanRestMs = 20000,
    this.connectionTimeoutMs = 15000,
    this.enableBackground = false,
    this.backgroundNotificationTitle = 'Mesh active',
    this.backgroundNotificationBody = 'Relaying messages to nearby devices.',
  });

  /// 128-bit service UUID the mesh advertises and scans for.
  String serviceUuid;

  /// Single read/write/notify characteristic that carries every frame.
  String characteristicUuid;

  /// Short advertised name. The advertisement budget is 31 bytes, so this goes
  /// in the scan response and should stay under ~12 characters.
  String advertisedName;

  /// Soft cap on simultaneous links. Android's hard limit is device-dependent
  /// (often 7) and exceeding it fails opaquely.
  int maxConcurrentLinks;

  /// Duty cycle for scanning. Android throttles apps to 5 `startScan` calls
  /// per 30s, so these values must stay well clear of that.
  int scanWindowMs;

  int scanRestMs;

  int connectionTimeoutMs;

  /// Android only: run inside a `connectedDevice` foreground service so the
  /// mesh survives backgrounding. iOS uses background modes instead.
  bool enableBackground;

  String backgroundNotificationTitle;

  String backgroundNotificationBody;

  List<Object?> _toList() {
    return <Object?>[
      serviceUuid,
      characteristicUuid,
      advertisedName,
      maxConcurrentLinks,
      scanWindowMs,
      scanRestMs,
      connectionTimeoutMs,
      enableBackground,
      backgroundNotificationTitle,
      backgroundNotificationBody,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleConfig decode(Object result) {
    result as List<Object?>;
    return BleConfig(
      serviceUuid: result[0]! as String,
      characteristicUuid: result[1]! as String,
      advertisedName: result[2]! as String,
      maxConcurrentLinks: result[3]! as int,
      scanWindowMs: result[4]! as int,
      scanRestMs: result[5]! as int,
      connectionTimeoutMs: result[6]! as int,
      enableBackground: result[7]! as bool,
      backgroundNotificationTitle: result[8]! as String,
      backgroundNotificationBody: result[9]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(serviceUuid, other.serviceUuid) && _deepEquals(characteristicUuid, other.characteristicUuid) && _deepEquals(advertisedName, other.advertisedName) && _deepEquals(maxConcurrentLinks, other.maxConcurrentLinks) && _deepEquals(scanWindowMs, other.scanWindowMs) && _deepEquals(scanRestMs, other.scanRestMs) && _deepEquals(connectionTimeoutMs, other.connectionTimeoutMs) && _deepEquals(enableBackground, other.enableBackground) && _deepEquals(backgroundNotificationTitle, other.backgroundNotificationTitle) && _deepEquals(backgroundNotificationBody, other.backgroundNotificationBody);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BleConfig(serviceUuid: $serviceUuid, characteristicUuid: $characteristicUuid, advertisedName: $advertisedName, maxConcurrentLinks: $maxConcurrentLinks, scanWindowMs: $scanWindowMs, scanRestMs: $scanRestMs, connectionTimeoutMs: $connectionTimeoutMs, enableBackground: $enableBackground, backgroundNotificationTitle: $backgroundNotificationTitle, backgroundNotificationBody: $backgroundNotificationBody)';
  }
}

/// One physical connection. Not a peer identity.
class BleLink {
  BleLink({
    required this.linkId,
    required this.role,
    required this.remoteId,
    required this.maxFrameSize,
    required this.connectedAtMs,
    this.rssi,
  });

  /// Opaque, stable for the lifetime of this connection.
  String linkId;

  BleLinkRole role;

  /// Platform device handle (Android MAC or iOS/macOS CBPeripheral UUID).
  /// Not stable across reboots on iOS and randomized on Android — never treat
  /// it as an identity.
  String remoteId;

  /// Largest frame that may be handed to [BleMeshHostApi.send] on this
  /// link. Dart fragments to this; the native side never fragments.
  int maxFrameSize;

  int connectedAtMs;

  int? rssi;

  List<Object?> _toList() {
    return <Object?>[
      linkId,
      role,
      remoteId,
      maxFrameSize,
      connectedAtMs,
      rssi,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleLink decode(Object result) {
    result as List<Object?>;
    return BleLink(
      linkId: result[0]! as String,
      role: result[1]! as BleLinkRole,
      remoteId: result[2]! as String,
      maxFrameSize: result[3]! as int,
      connectedAtMs: result[4]! as int,
      rssi: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleLink || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(linkId, other.linkId) && _deepEquals(role, other.role) && _deepEquals(remoteId, other.remoteId) && _deepEquals(maxFrameSize, other.maxFrameSize) && _deepEquals(connectedAtMs, other.connectedAtMs) && _deepEquals(rssi, other.rssi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BleLink(linkId: $linkId, role: $role, remoteId: $remoteId, maxFrameSize: $maxFrameSize, connectedAtMs: $connectedAtMs, rssi: $rssi)';
  }
}

/// One envelope for every event, carried on a single channel.
///
/// A single channel makes ordering structural rather than incidental: a frame
/// can never be delivered before the `linkUp` for its link.
class BleEvent {
  BleEvent({
    required this.kind,
    this.adapterState,
    this.link,
    this.linkId,
    this.frame,
    this.errorCode,
    this.message,
  });

  BleEventKind kind;

  /// Set when [kind] is [BleEventKind.adapterState].
  BleAdapterState? adapterState;

  /// Set when [kind] is [BleEventKind.linkUp].
  BleLink? link;

  /// Set for [BleEventKind.linkDown], [BleEventKind.frame], and for errors
  /// that are attributable to a specific link.
  String? linkId;

  /// Set when [kind] is [BleEventKind.frame].
  Uint8List? frame;

  /// Set when [kind] is [BleEventKind.error].
  BleErrorCode? errorCode;

  /// Human-readable detail for diagnostics. Never shown raw to end users.
  String? message;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      adapterState,
      link,
      linkId,
      frame,
      errorCode,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleEvent decode(Object result) {
    result as List<Object?>;
    return BleEvent(
      kind: result[0]! as BleEventKind,
      adapterState: result[1] as BleAdapterState?,
      link: result[2] as BleLink?,
      linkId: result[3] as String?,
      frame: result[4] as Uint8List?,
      errorCode: result[5] as BleErrorCode?,
      message: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(adapterState, other.adapterState) && _deepEquals(link, other.link) && _deepEquals(linkId, other.linkId) && _deepEquals(frame, other.frame) && _deepEquals(errorCode, other.errorCode) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BleEvent(kind: $kind, adapterState: $adapterState, link: $link, linkId: $linkId, frame: $frame, errorCode: $errorCode, message: $message)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BleAdapterState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BleLinkRole) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is BlePermissionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is BleErrorCode) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is BleEventKind) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is BleCapabilities) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BleConfig) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is BleLink) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is BleEvent) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleAdapterState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleLinkRole.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BlePermissionState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleErrorCode.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : BleEventKind.values[value];
      case 134:
        return BleCapabilities.decode(readValue(buffer)!);
      case 135:
        return BleConfig.decode(readValue(buffer)!);
      case 136:
        return BleLink.decode(readValue(buffer)!);
      case 137:
        return BleEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class BleMeshHostApi {
  /// Constructor for [BleMeshHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BleMeshHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<BleCapabilities> capabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BleCapabilities;
  }

  Future<BleAdapterState> adapterState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.adapterState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BleAdapterState;
  }

  Future<BlePermissionState> requestPermissions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BlePermissionState;
  }

  /// Starts advertising, the GATT server, and scanning. Idempotent.
  Future<void> start(BleConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Stops everything and drops all links. Idempotent.
  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sends one frame on one link.
  ///
  /// Completes when the platform has actually transmitted it (write callback
  /// or notification-sent callback), which is what gives Dart real
  /// backpressure instead of a fire-and-forget hose.
  Future<void> send(String linkId, Uint8List frame) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.send$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[linkId, frame]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect(String linkId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[linkId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<BleLink>> links() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ble_mesh.BleMeshHostApi.links$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BleLink>();
  }
}

/// Returns a broadcast [Stream] of events from the `events` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<BleEvent> events( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel =
      EventChannel('dev.flutter.pigeon.ble_mesh.BleMeshEventApi.events$instanceName', pigeonMethodCodec);
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as BleEvent;
  });
}
    
