// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.blemesh.ble_mesh

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object BleApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Power/authorization state of the host Bluetooth adapter. */
enum class BleAdapterState(val raw: Int) {
  /** Not yet reported by the platform. */
  UNKNOWN(0),
  /** No BLE radio, or the radio cannot do what the mesh needs. */
  UNSUPPORTED(1),
  /** The user denied Bluetooth permission, or it was never granted. */
  UNAUTHORIZED(2),
  /** Radio present but switched off. */
  POWERED_OFF(3),
  /** Ready to scan and advertise. */
  POWERED_ON(4);

  companion object {
    fun ofRaw(raw: Int): BleAdapterState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Which side of the connection we are on for a given link.
 *
 * A peer can be reachable over two links at once (we connected out, they
 * connected in). Collapsing links into peers is protocol-layer work in Dart.
 */
enum class BleLinkRole(val raw: Int) {
  /** We are the GATT client; we connected to their advertisement. */
  CENTRAL(0),
  /** We are the GATT server; they connected to our advertisement. */
  PERIPHERAL(1);

  companion object {
    fun ofRaw(raw: Int): BleLinkRole? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BlePermissionState(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  /**
   * Denied with "don't ask again" / restricted by policy. Only a trip to
   * system settings can change this, so the UI must say so.
   */
  PERMANENTLY_DENIED(2),
  /** The platform needs no runtime permission for this (e.g. macOS). */
  NOT_REQUIRED(3);

  companion object {
    fun ofRaw(raw: Int): BlePermissionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleErrorCode(val raw: Int) {
  BLUETOOTH_OFF(0),
  PERMISSION_DENIED(1),
  UNSUPPORTED(2),
  ADVERTISING_FAILED(3),
  SCAN_FAILED(4),
  CONNECTION_FAILED(5),
  WRITE_FAILED(6),
  /**
   * Not named `internal`: Pigeon would emit `case internal` in Swift, which
   * is a reserved word there.
   */
  INTERNAL_ERROR(7);

  companion object {
    fun ofRaw(raw: Int): BleErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleEventKind(val raw: Int) {
  ADAPTER_STATE(0),
  LINK_UP(1),
  LINK_DOWN(2),
  FRAME(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): BleEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What this device's radio can actually do.
 *
 * Plenty of budget Android hardware can scan but cannot advertise. Such a
 * device can still receive from the mesh but cannot be discovered, so the UI
 * must degrade honestly instead of pretending the mesh is healthy.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BleCapabilities (
  val supportsCentral: Boolean,
  val supportsPeripheral: Boolean,
  val platformName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleCapabilities {
      val supportsCentral = pigeonVar_list[0] as Boolean
      val supportsPeripheral = pigeonVar_list[1] as Boolean
      val platformName = pigeonVar_list[2] as String
      return BleCapabilities(supportsCentral, supportsPeripheral, platformName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportsCentral,
      supportsPeripheral,
      platformName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleCapabilities
    return BleApiPigeonUtils.deepEquals(this.supportsCentral, other.supportsCentral) && BleApiPigeonUtils.deepEquals(this.supportsPeripheral, other.supportsPeripheral) && BleApiPigeonUtils.deepEquals(this.platformName, other.platformName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.supportsCentral)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.supportsPeripheral)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.platformName)
    return result
  }
  override fun toString(): String {
    return "BleCapabilities(supportsCentral=$supportsCentral, supportsPeripheral=$supportsPeripheral, platformName=$platformName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConfig (
  /** 128-bit service UUID the mesh advertises and scans for. */
  val serviceUuid: String,
  /** Single read/write/notify characteristic that carries every frame. */
  val characteristicUuid: String,
  /**
   * Short advertised name. The advertisement budget is 31 bytes, so this goes
   * in the scan response and should stay under ~12 characters.
   */
  val advertisedName: String,
  /**
   * Soft cap on simultaneous links. Android's hard limit is device-dependent
   * (often 7) and exceeding it fails opaquely.
   */
  val maxConcurrentLinks: Long,
  /**
   * Duty cycle for scanning. Android throttles apps to 5 `startScan` calls
   * per 30s, so these values must stay well clear of that.
   */
  val scanWindowMs: Long,
  val scanRestMs: Long,
  val connectionTimeoutMs: Long,
  /**
   * Android only: run inside a `connectedDevice` foreground service so the
   * mesh survives backgrounding. iOS uses background modes instead.
   */
  val enableBackground: Boolean,
  val backgroundNotificationTitle: String,
  val backgroundNotificationBody: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleConfig {
      val serviceUuid = pigeonVar_list[0] as String
      val characteristicUuid = pigeonVar_list[1] as String
      val advertisedName = pigeonVar_list[2] as String
      val maxConcurrentLinks = pigeonVar_list[3] as Long
      val scanWindowMs = pigeonVar_list[4] as Long
      val scanRestMs = pigeonVar_list[5] as Long
      val connectionTimeoutMs = pigeonVar_list[6] as Long
      val enableBackground = pigeonVar_list[7] as Boolean
      val backgroundNotificationTitle = pigeonVar_list[8] as String
      val backgroundNotificationBody = pigeonVar_list[9] as String
      return BleConfig(serviceUuid, characteristicUuid, advertisedName, maxConcurrentLinks, scanWindowMs, scanRestMs, connectionTimeoutMs, enableBackground, backgroundNotificationTitle, backgroundNotificationBody)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuid,
      characteristicUuid,
      advertisedName,
      maxConcurrentLinks,
      scanWindowMs,
      scanRestMs,
      connectionTimeoutMs,
      enableBackground,
      backgroundNotificationTitle,
      backgroundNotificationBody,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleConfig
    return BleApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && BleApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && BleApiPigeonUtils.deepEquals(this.advertisedName, other.advertisedName) && BleApiPigeonUtils.deepEquals(this.maxConcurrentLinks, other.maxConcurrentLinks) && BleApiPigeonUtils.deepEquals(this.scanWindowMs, other.scanWindowMs) && BleApiPigeonUtils.deepEquals(this.scanRestMs, other.scanRestMs) && BleApiPigeonUtils.deepEquals(this.connectionTimeoutMs, other.connectionTimeoutMs) && BleApiPigeonUtils.deepEquals(this.enableBackground, other.enableBackground) && BleApiPigeonUtils.deepEquals(this.backgroundNotificationTitle, other.backgroundNotificationTitle) && BleApiPigeonUtils.deepEquals(this.backgroundNotificationBody, other.backgroundNotificationBody)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.advertisedName)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.maxConcurrentLinks)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.scanWindowMs)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.scanRestMs)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.connectionTimeoutMs)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.enableBackground)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.backgroundNotificationTitle)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.backgroundNotificationBody)
    return result
  }
  override fun toString(): String {
    return "BleConfig(serviceUuid=$serviceUuid, characteristicUuid=$characteristicUuid, advertisedName=$advertisedName, maxConcurrentLinks=$maxConcurrentLinks, scanWindowMs=$scanWindowMs, scanRestMs=$scanRestMs, connectionTimeoutMs=$connectionTimeoutMs, enableBackground=$enableBackground, backgroundNotificationTitle=$backgroundNotificationTitle, backgroundNotificationBody=$backgroundNotificationBody)"
  }
}

/**
 * One physical connection. Not a peer identity.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BleLink (
  /** Opaque, stable for the lifetime of this connection. */
  val linkId: String,
  val role: BleLinkRole,
  /**
   * Platform device handle (Android MAC or iOS/macOS CBPeripheral UUID).
   * Not stable across reboots on iOS and randomized on Android — never treat
   * it as an identity.
   */
  val remoteId: String,
  /**
   * Largest frame that may be handed to [BleMeshHostApi.send] on this
   * link. Dart fragments to this; the native side never fragments.
   */
  val maxFrameSize: Long,
  val connectedAtMs: Long,
  val rssi: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleLink {
      val linkId = pigeonVar_list[0] as String
      val role = pigeonVar_list[1] as BleLinkRole
      val remoteId = pigeonVar_list[2] as String
      val maxFrameSize = pigeonVar_list[3] as Long
      val connectedAtMs = pigeonVar_list[4] as Long
      val rssi = pigeonVar_list[5] as Long?
      return BleLink(linkId, role, remoteId, maxFrameSize, connectedAtMs, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      linkId,
      role,
      remoteId,
      maxFrameSize,
      connectedAtMs,
      rssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleLink
    return BleApiPigeonUtils.deepEquals(this.linkId, other.linkId) && BleApiPigeonUtils.deepEquals(this.role, other.role) && BleApiPigeonUtils.deepEquals(this.remoteId, other.remoteId) && BleApiPigeonUtils.deepEquals(this.maxFrameSize, other.maxFrameSize) && BleApiPigeonUtils.deepEquals(this.connectedAtMs, other.connectedAtMs) && BleApiPigeonUtils.deepEquals(this.rssi, other.rssi)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.linkId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.role)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.remoteId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.maxFrameSize)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.connectedAtMs)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.rssi)
    return result
  }
  override fun toString(): String {
    return "BleLink(linkId=$linkId, role=$role, remoteId=$remoteId, maxFrameSize=$maxFrameSize, connectedAtMs=$connectedAtMs, rssi=$rssi)"
  }
}

/**
 * One envelope for every event, carried on a single channel.
 *
 * A single channel makes ordering structural rather than incidental: a frame
 * can never be delivered before the `linkUp` for its link.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BleEvent (
  val kind: BleEventKind,
  /** Set when [kind] is [BleEventKind.adapterState]. */
  val adapterState: BleAdapterState? = null,
  /** Set when [kind] is [BleEventKind.linkUp]. */
  val link: BleLink? = null,
  /**
   * Set for [BleEventKind.linkDown], [BleEventKind.frame], and for errors
   * that are attributable to a specific link.
   */
  val linkId: String? = null,
  /** Set when [kind] is [BleEventKind.frame]. */
  val frame: ByteArray? = null,
  /** Set when [kind] is [BleEventKind.error]. */
  val errorCode: BleErrorCode? = null,
  /** Human-readable detail for diagnostics. Never shown raw to end users. */
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleEvent {
      val kind = pigeonVar_list[0] as BleEventKind
      val adapterState = pigeonVar_list[1] as BleAdapterState?
      val link = pigeonVar_list[2] as BleLink?
      val linkId = pigeonVar_list[3] as String?
      val frame = pigeonVar_list[4] as ByteArray?
      val errorCode = pigeonVar_list[5] as BleErrorCode?
      val message = pigeonVar_list[6] as String?
      return BleEvent(kind, adapterState, link, linkId, frame, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      adapterState,
      link,
      linkId,
      frame,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleEvent
    return BleApiPigeonUtils.deepEquals(this.kind, other.kind) && BleApiPigeonUtils.deepEquals(this.adapterState, other.adapterState) && BleApiPigeonUtils.deepEquals(this.link, other.link) && BleApiPigeonUtils.deepEquals(this.linkId, other.linkId) && BleApiPigeonUtils.deepEquals(this.frame, other.frame) && BleApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && BleApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BleApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.adapterState)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.link)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.linkId)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.frame)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + BleApiPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "BleEvent(kind=$kind, adapterState=$adapterState, link=$link, linkId=$linkId, frame=${frame?.contentToString()}, errorCode=$errorCode, message=$message)"
  }
}
private open class BleApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleAdapterState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleLinkRole.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BlePermissionState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleErrorCode.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleEventKind.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleCapabilities.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConfig.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleLink.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BleAdapterState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BleLinkRole -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BlePermissionState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BleErrorCode -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is BleEventKind -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is BleCapabilities -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BleConfig -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BleLink -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BleEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val BleApiPigeonMethodCodec = StandardMethodCodec(BleApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BleMeshHostApi {
  fun capabilities(): BleCapabilities
  fun adapterState(): BleAdapterState
  suspend fun requestPermissions(): BlePermissionState
  /** Starts advertising, the GATT server, and scanning. Idempotent. */
  suspend fun start(config: BleConfig)
  /** Stops everything and drops all links. Idempotent. */
  suspend fun stop()
  /**
   * Sends one frame on one link.
   *
   * Completes when the platform has actually transmitted it (write callback
   * or notification-sent callback), which is what gives Dart real
   * backpressure instead of a fire-and-forget hose.
   */
  suspend fun send(linkId: String, frame: ByteArray)
  suspend fun disconnect(linkId: String)
  fun links(): List<BleLink>

  companion object {
    /** The codec used by BleMeshHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BleApiPigeonCodec()
    }
    /** Sets up an instance of `BleMeshHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BleMeshHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.capabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.capabilities())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.adapterState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.adapterState())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermissions())
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as BleConfig
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.start(configArg)
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.stop()
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.send$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val linkIdArg = args[0] as String
            val frameArg = args[1] as ByteArray
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.send(linkIdArg, frameArg)
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val linkIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disconnect(linkIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                BleApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ble_mesh.BleMeshHostApi.links$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.links())
            } catch (exception: Throwable) {
              BleApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class BleApiPigeonStreamHandler<T>(
    val wrapper: BleApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface BleApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class EventsStreamHandler : BleApiPigeonEventChannelWrapper<BleEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.ble_mesh.BleMeshEventApi.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BleApiPigeonStreamHandler<BleEvent>(streamHandler)
      EventChannel(messenger, channelName, BleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BleApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<BleEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
